apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mcbprod
  name: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      namespace: mcbprod
      labels:
        app: api
    spec:
      imagePullSecrets:
      - name: myregistrykey2
      containers:
        - name: api
          image:  192.168.1.90:8888/mcbans-api:$BUILD_NUMBER
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "5Gi"
              cpu: "2000m"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: JAVA_OPTS
              value: "-Xms2g -Xmx5g"
            - name: MESH_NAME
              value: "mcbprod"
            - name: KAFKA_BROKER
              value: "192.168.88.146:9092,192.168.88.147:9092,192.168.88.145:9092"
