apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mcbprod
  name: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      namespace: mcbprod
      labels:
        app: api
    spec:
      containers:
        - name: api
          image:  192.168.1.170:30038/mcbans-api:$BUILD_NUMBER
