apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mcbprod
  name: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      namespace: mcbprod
      labels:
        app: api
    spec:
      containers:
        - name: api
          image:  192.168.1.170:30038/mcbans-api:$BUILD_NUMBER
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MESH_NAME
              value: "mcbprod"
            - name: KAFKA_BROKER
              value: "192.168.1.7:9092,192.168.1.6:9092"
